
services:
  app_db:
    image: postgres:17
    environment:
      POSTGRES_DB: pis_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
